"""Routes for downloading files from Daytona sandbox environments."""

from __future__ import annotations

import asyncio
import logging
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.auth.context import AuthContext
from app.db import DshMission, NewChatThread, Permission, get_async_session
from app.users import get_auth_context
from app.utils.rbac import check_permission

logger = logging.getLogger(__name__)

router = APIRouter()

MIME_TYPES: dict[str, str] = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".svg": "image/svg+xml",
    ".pdf": "application/pdf",
    ".csv": "text/csv",
    ".json": "application/json",
    ".txt": "text/plain",
    ".html": "text/html",
    ".md": "text/markdown",
    ".py": "text/x-python",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".zip": "application/zip",
}


def _guess_media_type(filename: str) -> str:
    ext = ("." + filename.rsplit(".", 1)[-1].lower()) if "." in filename else ""
    return MIME_TYPES.get(ext, "application/octet-stream")


@router.get("/threads/{thread_id}/sandbox/download")
async def download_sandbox_file(
    thread_id: int,
    path: str = Query(..., description="Absolute path of the file inside the sandbox"),
    session: AsyncSession = Depends(get_async_session),
    auth: AuthContext = Depends(get_auth_context),
):
    """Download a file from the Daytona sandbox associated with a chat thread."""

    from app.agents.chat.multi_agent_chat.shared.middleware.filesystem.sandbox import (
        get_or_create_sandbox,
        is_sandbox_enabled,
    )

    if not is_sandbox_enabled():
        raise HTTPException(status_code=404, detail="Sandbox is not enabled")

    result = await session.execute(
        select(NewChatThread).filter(NewChatThread.id == thread_id)
    )
    thread = result.scalars().first()
    if not thread:
        raise HTTPException(status_code=404, detail="Thread not found")

    await check_permission(
        session,
        auth,
        thread.workspace_id,
        Permission.CHATS_READ.value,
        "You don't have permission to access files in this thread",
    )

    from app.agents.chat.multi_agent_chat.shared.middleware.filesystem.sandbox import (
        get_local_sandbox_file,
    )

    # Prefer locally-persisted copy (sandbox may already be deleted)
    local_content = get_local_sandbox_file(thread_id, path)
    if local_content is not None:
        filename = path.rsplit("/", 1)[-1] if "/" in path else path
        media_type = _guess_media_type(filename)
        return Response(
            content=local_content,
            media_type=media_type,
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    # Fall back to live sandbox download
    try:
        sandbox, _ = await get_or_create_sandbox(thread_id)
        content: bytes = await asyncio.to_thread(sandbox.download_file, path)
    except Exception as exc:
        logger.warning("Sandbox file download failed for %s: %s", path, exc)
        raise HTTPException(
            status_code=404, detail=f"Could not download file: {exc}"
        ) from exc

    filename = path.rsplit("/", 1)[-1] if "/" in path else path
    media_type = _guess_media_type(filename)

    return Response(
        content=content,
        media_type=media_type,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/workspaces/{workspace_id}/dsh/missions/{mission_id}/deliverables/{filename}")
async def download_dsh_deliverable(
    workspace_id: int,
    mission_id: UUID,
    filename: str,
    include_pii: bool = Query(False, description="Request PII-included deliverable"),
    session: AsyncSession = Depends(get_async_session),
    auth: AuthContext = Depends(get_auth_context),
):
    """Download a deliverable file generated by a DSH mission.

    Requires ``LEADS_READ`` on the workspace. If ``include_pii=true`` the
    caller must still have ``LEADS_READ``; the backend only generated PII
    in the file when the mission was created with ``extras.include_pii=true``.
    """
    from app.agents.chat.multi_agent_chat.shared.middleware.filesystem.sandbox import (
        get_local_sandbox_file,
        get_or_create_sandbox,
        is_sandbox_enabled,
    )

    if not is_sandbox_enabled():
        raise HTTPException(status_code=404, detail="Sandbox is not enabled")

    result = await session.execute(
        select(DshMission)
        .filter(DshMission.id == mission_id)
        .filter(DshMission.workspace_id == workspace_id)
    )
    mission = result.scalars().first()
    if not mission:
        raise HTTPException(status_code=404, detail="Mission not found")

    await check_permission(
        session,
        auth,
        workspace_id,
        Permission.LEADS_READ.value,
        "You don't have permission to access DSH deliverables",
    )

    checkpoint = mission.checkpoint or {}
    deliverables = checkpoint.get("deliverables") or []
    deliverable = next(
        (d for d in deliverables if isinstance(d, dict) and d.get("filename") == filename),
        None,
    )
    if not deliverable:
        raise HTTPException(status_code=404, detail="Deliverable not found")

    sandbox_path = deliverable.get("sandbox_path")
    if not sandbox_path or not isinstance(sandbox_path, str):
        raise HTTPException(status_code=404, detail="Invalid deliverable path")

    local_content = get_local_sandbox_file(str(mission_id), sandbox_path)
    if local_content is not None:
        media_type = _guess_media_type(filename)
        return Response(
            content=local_content,
            media_type=media_type,
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    try:
        sandbox, _ = await get_or_create_sandbox(str(mission_id))
        content: bytes = await asyncio.to_thread(sandbox.download_file, sandbox_path)
    except Exception as exc:
        logger.warning("DSH deliverable download failed for %s: %s", sandbox_path, exc)
        raise HTTPException(
            status_code=404, detail=f"Could not download deliverable: {exc}"
        ) from exc

    media_type = _guess_media_type(filename)
    return Response(
        content=content,
        media_type=media_type,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
