"""Config domain: entities."""

from __future__ import annotations

import os

from app.config._helpers import (
    _env_int,
)

# Canonical entity settings
CANONICAL_EMBEDDING_OUTBOX_FAILURE_THRESHOLD = _env_int(
    "CANONICAL_EMBEDDING_OUTBOX_FAILURE_THRESHOLD", 5
)

# Signal detection (Story 21.1)
SIGNAL_SCAN_MICROS_PER_SIGNAL = max(0, _env_int("SIGNAL_SCAN_MICROS_PER_SIGNAL", 0))
LEAD_SCORING_MICROS_PER_CALL = max(0, _env_int("LEAD_SCORING_MICROS_PER_CALL", 0))
CRUNCHBASE_API_KEY = os.getenv("CRUNCHBASE_API_KEY", "")
NEWSAPI_KEY = os.getenv("NEWSAPI_KEY", "")
SIGNAL_EXECUTIVE_MOVE_ENABLED = (
    os.getenv("SIGNAL_EXECUTIVE_MOVE_ENABLED", "FALSE").upper() == "TRUE"
)
SIGNAL_EVENT_RETENTION_DAYS = max(1, _env_int("SIGNAL_EVENT_RETENTION_DAYS", 90))

# Contact enrichment (Story 21.3)
CLEANLIST_API_KEY = os.getenv("CLEANLIST_API_KEY", "")
BETTERCONTACT_API_KEY = os.getenv("BETTERCONTACT_API_KEY", "")
CONTACT_ENRICHMENT_MICROS_PER_CONTACT = max(
    0, _env_int("CONTACT_ENRICHMENT_MICROS_PER_CONTACT", 0)
)
CONTACT_ENRICHMENT_CACHE_TTL_SECONDS = max(
    1, _env_int("CONTACT_ENRICHMENT_CACHE_TTL_SECONDS", 30 * 24 * 60 * 60)
)
CONTACT_ENRICHMENT_PRIMARY_PROVIDER = (
    os.getenv("CONTACT_ENRICHMENT_PRIMARY_PROVIDER", "cleanlist").strip().lower()
)
CONTACT_ENRICHMENT_MAX_CONTACTS_PER_LEAD = max(
    1, _env_int("CONTACT_ENRICHMENT_MAX_CONTACTS_PER_LEAD", 5)
)
CONTACT_ENRICHMENT_REQUEST_TIMEOUT_SECONDS = max(
    1, _env_int("CONTACT_ENRICHMENT_REQUEST_TIMEOUT_SECONDS", 30)
)
CONTACT_ENRICHMENT_RETRY_ATTEMPTS = max(
    1, _env_int("CONTACT_ENRICHMENT_RETRY_ATTEMPTS", 3)
)

# CRM (Story 21.5)
SALESFORCE_CLIENT_ID = os.getenv("SALESFORCE_CLIENT_ID", "")
SALESFORCE_CLIENT_SECRET = os.getenv("SALESFORCE_CLIENT_SECRET", "")
SALESFORCE_REDIRECT_URI = os.getenv("SALESFORCE_REDIRECT_URI", "")
HUBSPOT_CLIENT_ID = os.getenv("HUBSPOT_CLIENT_ID", "")
HUBSPOT_CLIENT_SECRET = os.getenv("HUBSPOT_CLIENT_SECRET", "")
HUBSPOT_REDIRECT_URI = os.getenv("HUBSPOT_REDIRECT_URI", "")
PIPEDRIVE_CLIENT_ID = os.getenv("PIPEDRIVE_CLIENT_ID", "")
PIPEDRIVE_CLIENT_SECRET = os.getenv("PIPEDRIVE_CLIENT_SECRET", "")
PIPEDRIVE_REDIRECT_URI = os.getenv("PIPEDRIVE_REDIRECT_URI", "")
CRM_SYNC_DEDUP_ENABLED = (
    os.getenv("CRM_SYNC_DEDUP_ENABLED", "TRUE").upper() == "TRUE"
)
CRM_SYNC_WRITEBACK_ENABLED = (
    os.getenv("CRM_SYNC_WRITEBACK_ENABLED", "FALSE").upper() == "TRUE"
)
CRM_SYNC_BIDIRECTIONAL_ENABLED = (
    os.getenv("CRM_SYNC_BIDIRECTIONAL_ENABLED", "FALSE").upper() == "TRUE"
)
CRM_SYNC_BATCH_SIZE = max(1, _env_int("CRM_SYNC_BATCH_SIZE", 50))
CRM_SYNC_TIMEOUT_SECONDS = max(1, _env_int("CRM_SYNC_TIMEOUT_SECONDS", 30))
CRM_SYNC_TOKEN_REFRESH_LEEWAY_SECONDS = max(
    0, _env_int("CRM_SYNC_TOKEN_REFRESH_LEEWAY_SECONDS", 300)
)
# XActions local social ingress (Story 21.8)
XACTIONS_PATH = os.getenv("XACTIONS_PATH", "")
XACTIONS_TIMEOUT_SECONDS = _env_int("XACTIONS_TIMEOUT_SECONDS", 30)
XACTIONS_FACEBOOK_C_USER = os.getenv("XACTIONS_FACEBOOK_C_USER", "")
XACTIONS_FACEBOOK_XS = os.getenv("XACTIONS_FACEBOOK_XS", "")



__all__ = ['BETTERCONTACT_API_KEY', 'CANONICAL_EMBEDDING_OUTBOX_FAILURE_THRESHOLD', 'CLEANLIST_API_KEY', 'CONTACT_ENRICHMENT_CACHE_TTL_SECONDS', 'CONTACT_ENRICHMENT_MAX_CONTACTS_PER_LEAD', 'CONTACT_ENRICHMENT_MICROS_PER_CONTACT', 'CONTACT_ENRICHMENT_PRIMARY_PROVIDER', 'CONTACT_ENRICHMENT_REQUEST_TIMEOUT_SECONDS', 'CONTACT_ENRICHMENT_RETRY_ATTEMPTS', 'CRM_SYNC_BATCH_SIZE', 'CRM_SYNC_BIDIRECTIONAL_ENABLED', 'CRM_SYNC_DEDUP_ENABLED', 'CRM_SYNC_TIMEOUT_SECONDS', 'CRM_SYNC_TOKEN_REFRESH_LEEWAY_SECONDS', 'CRM_SYNC_WRITEBACK_ENABLED', 'CRUNCHBASE_API_KEY', 'HUBSPOT_CLIENT_ID', 'HUBSPOT_CLIENT_SECRET', 'HUBSPOT_REDIRECT_URI', 'LEAD_SCORING_MICROS_PER_CALL', 'NEWSAPI_KEY', 'PIPEDRIVE_CLIENT_ID', 'PIPEDRIVE_CLIENT_SECRET', 'PIPEDRIVE_REDIRECT_URI', 'SALESFORCE_CLIENT_ID', 'SALESFORCE_CLIENT_SECRET', 'SALESFORCE_REDIRECT_URI', 'SIGNAL_EVENT_RETENTION_DAYS', 'SIGNAL_EXECUTIVE_MOVE_ENABLED', 'SIGNAL_SCAN_MICROS_PER_SIGNAL', 'XACTIONS_FACEBOOK_C_USER', 'XACTIONS_FACEBOOK_XS', 'XACTIONS_PATH', 'XACTIONS_TIMEOUT_SECONDS']
