"""Config domain: media."""

from __future__ import annotations

import os

# Litellm TTS Configuration
TTS_SERVICE = os.getenv("TTS_SERVICE")
TTS_SERVICE_API_BASE = os.getenv("TTS_SERVICE_API_BASE")
TTS_SERVICE_API_KEY = os.getenv("TTS_SERVICE_API_KEY")

# STT Configuration
STT_SERVICE = os.getenv("STT_SERVICE")
STT_SERVICE_API_BASE = os.getenv("STT_SERVICE_API_BASE")
STT_SERVICE_API_KEY = os.getenv("STT_SERVICE_API_KEY")

# Video presentation defaults
VIDEO_PRESENTATION_MAX_SLIDES = int(
    os.getenv("VIDEO_PRESENTATION_MAX_SLIDES", "30")
)
VIDEO_PRESENTATION_FPS = int(os.getenv("VIDEO_PRESENTATION_FPS", "30"))
VIDEO_PRESENTATION_DEFAULT_DURATION_IN_FRAMES = int(
    os.getenv("VIDEO_PRESENTATION_DEFAULT_DURATION_IN_FRAMES", "300")
)



__all__ = ['STT_SERVICE', 'STT_SERVICE_API_BASE', 'STT_SERVICE_API_KEY', 'TTS_SERVICE', 'TTS_SERVICE_API_BASE', 'TTS_SERVICE_API_KEY', 'VIDEO_PRESENTATION_DEFAULT_DURATION_IN_FRAMES', 'VIDEO_PRESENTATION_FPS', 'VIDEO_PRESENTATION_MAX_SLIDES']
