"""Config domain: web_builder."""

from __future__ import annotations

import os

from app.config._helpers import (
    BASE_DIR,
    _env_int,
)

# Instant web-app hosting / builder (Story 27.1) - See line 1808 for canonical definition

# Web Builder & 1-Click Hosting (Story 27.1 / AD-113 / AD-114)
HOSTING_BASE_DOMAIN = os.getenv("HOSTING_BASE_DOMAIN", "apps.nowing.net")
CNAME_INGRESS_HOST = os.getenv(
    "CNAME_INGRESS_HOST", "cname-ingress.apps.nowing.net"
)
FILE_STORAGE_LOCAL_PATH = os.getenv(
    "FILE_STORAGE_LOCAL_PATH",
    # Anchor the default to the project root so it is independent of the
    # worker process CWD (e.g. Celery vs. web server).
    str(BASE_DIR / ".local_object_store"),
)
WEB_BUILDER_ENABLED = os.getenv("WEB_BUILDER_ENABLED", "TRUE").upper() == "TRUE"
WEB_BUILDER_MAX_PROMPT_CHARS = max(
    1, _env_int("WEB_BUILDER_MAX_PROMPT_CHARS", 2000)
)
WEB_BUILDER_PUBLIC_APPS_PATH = os.getenv(
    "WEB_BUILDER_PUBLIC_APPS_PATH",
    f"{FILE_STORAGE_LOCAL_PATH}/web-apps",
)
# Small fixed platform fee for static-snapshot deploy (default $0 for Option A).
WEB_BUILDER_DEPLOY_COST_MICROS = max(
    0, _env_int("WEB_BUILDER_DEPLOY_COST_MICROS", 0)
)
WEB_BUILDER_BUILD_COST_MICROS = max(0, _env_int("WEB_BUILDER_BUILD_COST_MICROS", 0))
WEB_BUILDER_BUILD_TIMEOUT_SECONDS = max(
    10, _env_int("WEB_BUILDER_BUILD_TIMEOUT_SECONDS", 300)
)
WEB_BUILDER_MAX_CONCURRENT_BUILDS = max(
    1, _env_int("WEB_BUILDER_MAX_CONCURRENT_BUILDS", 3)
)
WEB_BUILDER_BUILD_NODE_VERSION = os.getenv("WEB_BUILDER_BUILD_NODE_VERSION", "20")
WEB_BUILDER_BUILD_NODE_IMAGE_DIGEST = os.getenv(
    "WEB_BUILDER_BUILD_NODE_IMAGE_DIGEST", ""
).strip()
WEB_BUILDER_DOCKER_SANDBOX_ENABLED = (
    os.getenv("WEB_BUILDER_DOCKER_SANDBOX_ENABLED", "FALSE").upper() == "TRUE"
)
WEB_BUILDER_CONTAINER_DEPLOY_ENABLED = (
    os.getenv("WEB_BUILDER_CONTAINER_DEPLOY_ENABLED", "FALSE").upper() == "TRUE"
)
WEB_BUILDER_DOKPLOY_NETWORK = os.getenv(
    "WEB_BUILDER_DOKPLOY_NETWORK", "dokploy-network"
)
# Container healthcheck / lifecycle tuning.
WEB_BUILDER_CONTAINER_HEALTHCHECK_TIMEOUT = max(
    5, _env_int("WEB_BUILDER_CONTAINER_HEALTHCHECK_TIMEOUT", 60)
)
WEB_BUILDER_CONTAINER_HEALTHCHECK_RETRIES = max(
    1, _env_int("WEB_BUILDER_CONTAINER_HEALTHCHECK_RETRIES", 10)
)

# Self-host Caddy dynamic snippet config.
# Operators enable these for the Caddy 2 file-provider fallback (Story 27.1c).
WEB_BUILDER_CADDY_SNIPPETS_ENABLED = (
    os.getenv("WEB_BUILDER_CADDY_SNIPPETS_ENABLED", "FALSE").upper() == "TRUE"
)
WEB_BUILDER_CADDY_SNIPPETS_PATH = os.getenv(
    "WEB_BUILDER_CADDY_SNIPPETS_PATH",
    "docker/proxy/web-apps.Caddyfile",
)
WEB_BUILDER_CADDY_RELOAD_ENABLED = (
    os.getenv("WEB_BUILDER_CADDY_RELOAD_ENABLED", "FALSE").upper() == "TRUE"
)
WEB_BUILDER_CADDY_CONTAINER_NAME = os.getenv("WEB_BUILDER_CADDY_CONTAINER_NAME", "")
WEB_BUILDER_CADDY_BACKEND_TARGET = os.getenv(
    "WEB_BUILDER_CADDY_BACKEND_TARGET", "backend:8000"
)

# Health probe targets for optional infrastructure components.
# When unset, the probe reports "not_configured" instead of failing against localhost.
CADDY_ADMIN_URL = os.getenv("CADDY_ADMIN_URL", "")
ZERO_CACHE_KEEPALIVE_URL = os.getenv("ZERO_CACHE_KEEPALIVE_URL", "")

# Production Traefik label overrides.
WEB_BUILDER_TRAEFIK_ENTRYPOINT = os.getenv(
    "WEB_BUILDER_TRAEFIK_ENTRYPOINT", "websecure"
)
WEB_BUILDER_TRAEFIK_CERTRESOLVER = os.getenv(
    "WEB_BUILDER_TRAEFIK_CERTRESOLVER", "default"
)
WEB_BUILDER_TRAEFIK_USE_TLS = (
    os.getenv("WEB_BUILDER_TRAEFIK_USE_TLS", "TRUE").upper() == "TRUE"
)

# Reserved domain blacklist (comma-separated) in addition to the configured base domain.
WEB_BUILDER_DOMAIN_BLACKLIST = os.getenv("WEB_BUILDER_DOMAIN_BLACKLIST", "")

USE_DYNAMIC_SCRAPER_RULES = (
    os.getenv("USE_DYNAMIC_SCRAPER_RULES", "FALSE").upper() == "TRUE"
)

PRESENTATION_STUDIO_ENABLED = (
    os.getenv("PRESENTATION_STUDIO_ENABLED", "FALSE").upper() == "TRUE"
)
PRESENTATION_MAX_PROMPT_CHARS = max(
    1, _env_int("PRESENTATION_MAX_PROMPT_CHARS", 2000)
)
PRESENTATION_FILE_STORAGE_SUBDIR = os.getenv(
    "PRESENTATION_FILE_STORAGE_SUBDIR", "presentations"
)

MEETING_MINUTES_ENABLED = (
    os.getenv("MEETING_MINUTES_ENABLED", "FALSE").upper() == "TRUE"
)
MEETING_MINUTES_MAX_PROMPT_CHARS = max(
    1, _env_int("MEETING_MINUTES_MAX_PROMPT_CHARS", 2000)
)
MEETING_MINUTES_MAX_DURATION_SECONDS = max(
    1, _env_int("MEETING_MINUTES_MAX_DURATION_SECONDS", 600)
)
MEETING_MINUTES_TRANSCRIPTION_MICROS_PER_SECOND = max(
    0, _env_int("MEETING_MINUTES_TRANSCRIPTION_MICROS_PER_SECOND", 0)
)
MEETING_MINUTES_MAX_AUDIO_BYTES = max(
    1, _env_int("MEETING_MINUTES_MAX_AUDIO_BYTES", 100 * 1024 * 1024)
)
MEETING_MINUTES_DIARIZATION_ENGINE = os.getenv(
    "MEETING_MINUTES_DIARIZATION_ENGINE", "pyannote"
).lower()
MEETING_MINUTES_MAX_SPEAKER_LABELS = max(
    1, _env_int("MEETING_MINUTES_MAX_SPEAKER_LABELS", 10)
)
HUGGINGFACE_TOKEN = os.getenv("HUGGINGFACE_TOKEN", "")

__all__ = ['CADDY_ADMIN_URL', 'CNAME_INGRESS_HOST', 'FILE_STORAGE_LOCAL_PATH', 'HOSTING_BASE_DOMAIN', 'HUGGINGFACE_TOKEN', 'MEETING_MINUTES_DIARIZATION_ENGINE', 'MEETING_MINUTES_ENABLED', 'MEETING_MINUTES_MAX_AUDIO_BYTES', 'MEETING_MINUTES_MAX_DURATION_SECONDS', 'MEETING_MINUTES_MAX_PROMPT_CHARS', 'MEETING_MINUTES_MAX_SPEAKER_LABELS', 'MEETING_MINUTES_TRANSCRIPTION_MICROS_PER_SECOND', 'PRESENTATION_FILE_STORAGE_SUBDIR', 'PRESENTATION_MAX_PROMPT_CHARS', 'PRESENTATION_STUDIO_ENABLED', 'USE_DYNAMIC_SCRAPER_RULES', 'WEB_BUILDER_BUILD_COST_MICROS', 'WEB_BUILDER_BUILD_NODE_IMAGE_DIGEST', 'WEB_BUILDER_BUILD_NODE_VERSION', 'WEB_BUILDER_BUILD_TIMEOUT_SECONDS', 'WEB_BUILDER_CADDY_BACKEND_TARGET', 'WEB_BUILDER_CADDY_CONTAINER_NAME', 'WEB_BUILDER_CADDY_RELOAD_ENABLED', 'WEB_BUILDER_CADDY_SNIPPETS_ENABLED', 'WEB_BUILDER_CADDY_SNIPPETS_PATH', 'WEB_BUILDER_CONTAINER_DEPLOY_ENABLED', 'WEB_BUILDER_CONTAINER_HEALTHCHECK_RETRIES', 'WEB_BUILDER_CONTAINER_HEALTHCHECK_TIMEOUT', 'WEB_BUILDER_DEPLOY_COST_MICROS', 'WEB_BUILDER_DOCKER_SANDBOX_ENABLED', 'WEB_BUILDER_DOKPLOY_NETWORK', 'WEB_BUILDER_DOMAIN_BLACKLIST', 'WEB_BUILDER_ENABLED', 'WEB_BUILDER_MAX_CONCURRENT_BUILDS', 'WEB_BUILDER_MAX_PROMPT_CHARS', 'WEB_BUILDER_PUBLIC_APPS_PATH', 'WEB_BUILDER_TRAEFIK_CERTRESOLVER', 'WEB_BUILDER_TRAEFIK_ENTRYPOINT', 'WEB_BUILDER_TRAEFIK_USE_TLS', 'ZERO_CACHE_KEEPALIVE_URL']
