"""Batdongsan city code / web slug mapping (proprietary, BSL 1.1)."""

from __future__ import annotations

CITY_SLUGS: dict[str, str] = {
    "AG": "an-giang",
    "BD": "binh-duong",
    "BDI": "binh-dinh",
    "BG": "bac-giang",
    "BK": "bac-kan",
    "BL": "bac-lieu",
    "BN": "bac-ninh",
    "BP": "binh-phuoc",
    "BT": "ben-tre",
    "BTH": "binh-thuan",
    "CB": "cao-bang",
    "CM": "ca-mau",
    "CT": "can-tho",
    "DI": "dien-bien",
    "DKL": "dak-lak",
    "DN": "da-nang",
    "DNO": "dak-nong",
    "DT": "dong-thap",
    "GL": "gia-lai",
    "HD": "hai-duong",
    "HG": "ha-giang",
    "HN": "ha-noi",
    "HP": "hai-phong",
    "HT": "ha-tinh",
    "HUG": "hau-giang",
    "HY": "hung-yen",
    "KH": "khanh-hoa",
    "KG": "kien-giang",
    "KT": "kon-tum",
    "LA": "long-an",
    "LB": "long-bien",
    "LC": "lao-cai",
    "LCH": "lai-chau",
    "LD": "lam-dong",
    "LS": "lang-son",
    "NA": "nghe-an",
    "NB": "ninh-binh",
    "ND": "nam-dinh",
    "NT": "ninh-thuan",
    "PT": "phu-tho",
    "PY": "phu-yen",
    "QB": "quang-binh",
    "QN": "quang-ninh",
    "QNG": "quang-ngai",
    "QT": "quang-tri",
    "SG": "tp-hcm",
    "SL": "son-la",
    "ST": "soc-trang",
    "TB": "thai-binh",
    "TG": "tien-giang",
    "TH": "thanh-hoa",
    "TN": "thai-nguyen",
    "TQ": "tuyen-quang",
    "TV": "tra-vinh",
    "TTH": "hue",
    "VL": "vinh-long",
    "VT": "ba-ria-vung-tau",
    "YB": "yen-bai",
}

CITY_CODES: frozenset[str] = frozenset(CITY_SLUGS)
