"""OpenTelemetry metrics facade for Nowing.

Domain modules live alongside this file. This facade re-exports the public
surface so existing callers can continue using
``from app.observability.metrics import X``.
"""

from __future__ import annotations

from app.observability.metrics.base import (
    _add,
    _record,
    categorize_exception,
    parse_celery_task_label,
)
from app.observability.metrics.etl import (
    record_celery_heartbeat_failure,
    record_celery_heartbeat_refresh,
    record_celery_queue_latency,
    record_chunk_reconcile,
    record_connector_sync_duration,
    record_connector_sync_outcome,
    record_embedding_cache_eviction,
    record_embedding_cache_lookup,
    record_etl_cache_eviction,
    record_etl_cache_lookup,
    record_etl_extract_duration,
    record_etl_extract_outcome,
    record_indexing_document_duration,
    record_indexing_document_outcome,
)
from app.observability.metrics.gateway import (
    record_gateway_active_bindings_delta,
    record_gateway_auth_invariant_failure,
    record_gateway_byo_longpoll_running_delta,
    record_gateway_health_check_failure,
    record_gateway_hitl_aborted,
    record_gateway_inbound_reconciled,
    record_gateway_inbox_enqueued,
    record_gateway_inbox_processed,
    record_gateway_inbox_sweep_replayed,
    record_gateway_inbox_write,
    record_gateway_outbound,
    record_gateway_rate_limit_hit,
    record_gateway_redis_fallback,
    record_gateway_thread_lock_contention,
    record_gateway_turn_latency,
    record_gateway_webhook_parse_error,
)
from app.observability.metrics.genai import (
    record_agent_chat_public_call,
    record_chat_request_duration,
    record_chat_request_outcome,
    record_compaction_run,
    record_interrupt,
    record_kb_search_duration,
    record_model_call_duration,
    record_model_token_usage,
    record_permission_ask,
    record_subagent_invoke_duration,
    record_subagent_invoke_outcome,
    record_tool_call_duration,
    record_tool_call_error,
)
from app.observability.metrics.memory import (
    record_memory_injection_failure,
    record_memory_injection_truncated,
    record_run_memory_created,
    record_run_memory_enqueued,
    record_run_memory_failed,
    record_run_memory_retried,
    record_run_memory_skipped,
    record_run_memory_zero_fact,
)
from app.observability.metrics.platform import (
    record_auth_failure,
    record_perf_elapsed,
    record_rate_limit_rejection,
    record_run_event_bus_dropped,
)
from app.observability.metrics.research import (
    record_anti_bot_detection,
    record_anti_bot_screenshot_failure,
    record_blocked_url_coverage,
    record_chainlens_auth_failed,
    record_chainlens_degradation,
    record_chainlens_ingest_failed,
    record_chainlens_latency,
    record_chainlens_private_search,
    record_chainlens_token_rotated,
    record_kb_fallback_hit_count,
    record_vn_jobs_aggregate_degraded,
    record_vn_jobs_pii_detected,
    record_vn_jobs_source_block,
)
from app.observability.metrics.runtime import register_runtime_observables

__all__ = [
    "_add",
    "_record",
    "categorize_exception",
    "parse_celery_task_label",
    "record_agent_chat_public_call",
    "record_anti_bot_detection",
    "record_anti_bot_screenshot_failure",
    "record_auth_failure",
    "record_blocked_url_coverage",
    "record_celery_heartbeat_failure",
    "record_celery_heartbeat_refresh",
    "record_celery_queue_latency",
    "record_chainlens_auth_failed",
    "record_chainlens_degradation",
    "record_chainlens_ingest_failed",
    "record_chainlens_latency",
    "record_chainlens_private_search",
    "record_chainlens_token_rotated",
    "record_chat_request_duration",
    "record_chat_request_outcome",
    "record_chunk_reconcile",
    "record_compaction_run",
    "record_connector_sync_duration",
    "record_connector_sync_outcome",
    "record_embedding_cache_eviction",
    "record_embedding_cache_lookup",
    "record_etl_cache_eviction",
    "record_etl_cache_lookup",
    "record_etl_extract_duration",
    "record_etl_extract_outcome",
    "record_gateway_active_bindings_delta",
    "record_gateway_auth_invariant_failure",
    "record_gateway_byo_longpoll_running_delta",
    "record_gateway_health_check_failure",
    "record_gateway_hitl_aborted",
    "record_gateway_inbound_reconciled",
    "record_gateway_inbox_enqueued",
    "record_gateway_inbox_processed",
    "record_gateway_inbox_sweep_replayed",
    "record_gateway_inbox_write",
    "record_gateway_outbound",
    "record_gateway_rate_limit_hit",
    "record_gateway_redis_fallback",
    "record_gateway_thread_lock_contention",
    "record_gateway_turn_latency",
    "record_gateway_webhook_parse_error",
    "record_indexing_document_duration",
    "record_indexing_document_outcome",
    "record_interrupt",
    "record_kb_fallback_hit_count",
    "record_kb_search_duration",
    "record_memory_injection_failure",
    "record_memory_injection_truncated",
    "record_model_call_duration",
    "record_model_token_usage",
    "record_perf_elapsed",
    "record_permission_ask",
    "record_rate_limit_rejection",
    "record_run_event_bus_dropped",
    "record_run_memory_created",
    "record_run_memory_enqueued",
    "record_run_memory_failed",
    "record_run_memory_retried",
    "record_run_memory_skipped",
    "record_run_memory_zero_fact",
    "record_subagent_invoke_duration",
    "record_subagent_invoke_outcome",
    "record_tool_call_duration",
    "record_tool_call_error",
    "record_vn_jobs_aggregate_degraded",
    "record_vn_jobs_pii_detected",
    "record_vn_jobs_source_block",
    "register_runtime_observables",
]
